<details>
  <summary><b>Error handling</b></summary>
  Dart 코드에서는 예외를 발생시키고 잡을 수 있습니다. 예외는 예기치 않은 일이 발생했음을 나타내는 오류입니다. 예외가 잡히지 않으면, 예외를 발생시킨 아이솔레이트가 일시 중단되고, 일반적으로 아이솔레이트와 그 프로그램이 종료됩니다.

### Isolates

아이솔레이트를 사용하면 Dart 코드는 추가 프로세서 코어를 사용할 수 있는 경우 여러 개의 독립적인 작업을 동시에 수행할 수 있습니다. 아이솔레이트는 스레드나 프로세스와 비슷하지만, 각 아이솔레이트는 자체 메모리와 이벤트 루프를 실행하는 단일 스레드를 가지고 있습니다.

### **Throw**

- 하나의 표현식이기 때문에, `=>` 문이나 다른 표현식으로 예외를 발생시킬 수 있습니다.
- 임의의 객체도 던질 수 있습니다.

### **Catch**

앞서 나온 코드에서 알 수 있듯이, `on` 또는 `catch` 또는 둘 다 사용할 수 있습니다. 예외 타입을 지정해야 할 때는 `on`을 사용하고, 예외 객체가 필요한 경우에는 `catch`를 사용합니다.

catch()에 하나 또는 두 개의 매개변수를 지정할 수 있습니다. 첫 번째는 던져진 예외이며, 두 번째는 스택 추적(StackTrace) 객체입니다.

### rethrow

- `rethrow`는 Dart에서 예외를 부분적으로 처리한 후 해당 예외를 다시 던져 상위 호출자에게 전파하기 위해 사용하는 키워드입니다.
- **추가 로깅 또는 처리**: 예외가 발생한 시점에 추가 정보를 로깅하거나 일부 상태를 변경한 후 상위 호출자에게 예외를 전파할 수 있습니다.
- **예외 전파**: 예외를 완전히 처리하지 않고, 상위 호출자가 예외를 처리하도록 허용할 수 있습니다.

### finally

예외가 발생하든 발생하지 않든 일부 코드가 항상 실행되도록 하려면 `finally` 절을 사용합니다.

### assert

개발 중에 assert 문(assert(<조건>, <선택적 메시지>);)을 사용하여 boolean 조건이 false인 경우 assert가 실패하고 예외(AssertionError)가 발생합니다.

```dart
assert(urlString.startsWith('https'),
    'URL ($urlString) should start with "https".');
```

- Flutter는 디버그 모드에서 assert를 활성화합니다.
- 웹 개발 툴인 webdev serve는 기본적으로 assert를 활성화합니다.
- dart run 및 dart compile js와 같은 일부 도구는 명령 줄 플래그(--enable-asserts)를 통해 assert를 지원합니다.
- 프로덕션 코드에서는 assert가 무시되며, assert의 인수는 평가되지 않습니다.
</details>
