# Asynchronous programming: futures, async, await

This tutorial teaches you how to write asynchronous code using futures and the `async` and `await` keywords. Using embedded DartPad editors, you can test your knowledge by running example code and completing exercises.

To get the most out of this tutorial, you should have the following:

- Knowledge of [basic Dart syntax](https://dart.dev/language).
- Some experience writing asynchronous code in another language.

This tutorial covers the following material:

- How and when to use the `async` and `await` keywords.
- How using `async` and `await` affects execution order.
- How to handle errors from an asynchronous call using `try-catch` expressions in `async` functions.

Estimated time to complete this tutorial: 40-60 minutes.

이 튜토리얼은 `async` 및 `await` 키워드를 사용하여 비동기 코드를 작성하는 방법을 가르칩니다. 내장된 DartPad 편집기를 사용하여 예제 코드를 실행하고 연습 문제를 완료함으로써 지식을 테스트할 수 있습니다.

이 튜토리얼을 최대한 활용하려면 다음이 필요합니다:

- 기본 Dart 구문에 대한 지식.
- 다른 언어에서 비동기 코드를 작성한 경험.

이 튜토리얼은 다음 자료를 다룹니다:

- `async` 및 `await` 키워드를 사용하는 방법 및 시기.
- `async` 및 `await`를 사용하는 것이 실행 순서에 미치는 영향.
- `async` 함수에서 `try-catch` 표현식을 사용하여 비동기 호출의 오류를 처리하는 방법.

이 튜토리얼을 완료하는 데 예상 소요 시간: 40-60분.

The exercises in this tutorial have partially completed code snippets. You can use DartPad to test your knowledge by completing the code and clicking the **Run** button. **Don't edit the test code in the `main` function or below**.

If you need help, expand the **Hint** or **Solution** dropdown after each exercise.

이 튜토리얼의 연습 문제에는 부분적으로 완료된 코드 조각이 있습니다. DartPad를 사용하여 코드를 완성하고 실행 버튼을 클릭하여 지식을 테스트할 수 있습니다. main 함수나 그 아래의 테스트 코드를 편집하지 마십시오.

도움이 필요하면 각 연습 문제 후에 힌트 또는 솔루션 드롭다운을 확장하십시오.

## Why asynchronous code matters

Asynchronous operations let your program complete work while waiting for another operation to finish. Here are some common asynchronous operations:

- Fetching data over a network.
- Writing to a database.
- Reading data from a file.

Such asynchronous computations usually provide their result as a `Future` or, if the result has multiple parts, as a `Stream`. These computations introduce asynchrony into a program. To accommodate that initial asynchrony, other plain Dart functions also need to become asynchronous.

To interact with these asynchronous results, you can use the `async` and `await` keywords. Most asynchronous functions are just async Dart functions that depend, possibly deep down, on an inherently asynchronous computation.

## 비동기 코드가 중요한 이유

비동기 작업을 통해 프로그램은 다른 작업이 완료되기를 기다리는 동안 작업을 완료할 수 있습니다. 다음은 일반적인 비동기 작업입니다:

네트워크를 통해 데이터 가져오기. 데이터베이스에 쓰기. 파일에서 데이터 읽기. 
이러한 비동기 계산은 일반적으로 결과를 Future로 제공하거나, 결과가 여러 부분인 경우 Stream으로 제공합니다. 이러한 계산은 프로그램에 비동기를 도입합니다. 초기 비동기를 수용하기 위해 다른 평범한 Dart 함수도 비동기 함수가 되어야 합니다.

이러한 비동기 결과와 상호 작용하려면 async 및 await 키워드를 사용할 수 있습니다. 대부분의 비동기 함수는 기본적으로 비동기 계산에 의존하는 비동기 Dart 함수입니다.

### Example: Incorrectly using an asynchronous function

The following example shows the wrong way to use an asynchronous function (`fetchUserOrder()`). Later you'll fix the example using `async` and `await`. Before running this example, try to spot the issue -- what do you think the output will be?

### 예제: 비동기 함수를 잘못 사용하는 경우

다음 예제는 비동기 함수(fetchUserOrder())를 잘못 사용하는 방법을 보여줍니다. 나중에 async 및 await를 사용하여 예제를 수정할 것입니다. 이 예제를 실행하기 전에 문제가 무엇인지 찾아보십시오 -- 출력이 어떻게 될 것 같습니까?

```dart
// This example shows how *not* to write asynchronous Dart code.

String createOrderMessage() {
  var order = fetchUserOrder();
  return 'Your order is: $order';
}

Future<String> fetchUserOrder() =>
    // Imagine that this function is more complex and slow.
    Future.delayed(
      const Duration(seconds: 2),
      () => 'Large Latte',
    );

void main() {
  print(createOrderMessage());
}
```

```
Your order is: Instance of '_Future<String>'
```



Here's why the example fails to print the value that `fetchUserOrder()` eventually produces:

- `fetchUserOrder()` is an asynchronous function that, after a delay, provides a string that describes the user's order: a "Large Latte".
- To get the user's order, `createOrderMessage()` should call `fetchUserOrder()` and wait for it to finish. Because `createOrderMessage()` does _not_ wait for `fetchUserOrder()` to finish, `createOrderMessage()` fails to get the string value that `fetchUserOrder()` eventually provides.
- Instead, `createOrderMessage()` gets a representation of pending work to be done: an uncompleted future. You'll learn more about futures in the next section.
- Because `createOrderMessage()` fails to get the value describing the user's order, the example fails to print "Large Latte" to the console, and instead prints "Your order is: Instance of '_Future\<String>'".

In the next sections you'll learn about futures and about working with futures (using `async` and `await`) so that you'll be able to write the code necessary to make `fetchUserOrder()` print the desired value ("Large Latte") to the console.

다음은 `fetchUserOrder()`가 결국 생성하는 값을 예제가 출력하지 못하는 이유입니다:

- `fetchUserOrder()`는 지연 후 사용자의 주문을 설명하는 문자열인 "Large Latte"를 제공하는 비동기 함수입니다.
- 사용자의 주문을 받으려면 `createOrderMessage()`는 `fetchUserOrder()`를 호출하고 완료될 때까지 기다려야 합니다. 그러나 `createOrderMessage()`는 `fetchUserOrder()`가 완료될 때까지 기다리지 않기 때문에, `createOrderMessage()`는 결국 `fetchUserOrder()`가 제공하는 문자열 값을 얻지 못합니다.
- 대신, `createOrderMessage()`는 완료되지 않은 작업의 표현인 완료되지 않은 future를 얻습니다. 다음 섹션에서 future에 대해 더 배울 것입니다.
- `createOrderMessage()`가 사용자의 주문을 설명하는 값을 얻지 못하기 때문에, 예제는 콘솔에 "Large Latte"를 출력하지 못하고 대신 "Your order is: Instance of '_Future\<String>'"를 출력합니다.

다음 섹션에서는 futures와 futures를 다루는 방법(`async`와 `await` 사용)에 대해 배워서 `fetchUserOrder()`가 콘솔에 원하는 값("Large Latte")을 출력하도록 코드를 작성할 수 있게 될 것입니다.

Key terms

- **synchronous operation**: A synchronous operation blocks other operations from executing until it completes.
- **synchronous function**: A synchronous function only performs synchronous operations.
- **asynchronous operation**: Once initiated, an asynchronous operation allows other operations to execute before it completes.
- **asynchronous function**: An asynchronous function performs at least one asynchronous operation and can also perform _synchronous_ operations.

주요 용어

- **동기 작업**: 동기 작업은 완료될 때까지 다른 작업의 실행을 차단합니다.
- **동기 함수**: 동기 함수는 동기 작업만 수행합니다.
- **비동기 작업**: 일단 시작되면, 비동기 작업은 완료되기 전에 다른 작업이 실행될 수 있도록 합니다.
- **비동기 함수**: 비동기 함수는 최소한 하나의 비동기 작업을 수행하며, 동기 작업도 수행할 수 있습니다.

## What is a future?

A future (lower case "f") is an instance of the [Future](https://api.dart.dev/stable/dart-async/Future-class.html) (capitalized "F") class. A future represents the result of an asynchronous operation, and can have two states: uncompleted or completed.

## future란 무엇인가?

future(소문자 "f")는 Future(대문자 "F") 클래스의 인스턴스입니다. future는 비동기 작업의 결과를 나타내며, 완료되지 않은 상태 또는 완료된 상태의 두 가지 상태를 가질 수 있습니다.

_Note_

_Uncompleted_ is a Dart term referring to the state of a future before it has produced a value.

_정보_

"Uncompleted" (미완료된)은 Dart에서 future가 값(결과)을 생성하기 전의 상태를 나타내는 용어입니다.
### Uncompleted

When you call an asynchronous function, it returns an uncompleted future. That future is waiting for the function's asynchronous operation to finish or to throw an error.

### 미완료된

비동기 함수를 호출하면 미완료된 future가 반환됩니다. 이 future는 함수의 비동기 작업이 완료되거나 오류가 발생할 때까지 기다립니다.

### Completed

If the asynchronous operation succeeds, the future completes with a value. Otherwise, it completes with an error.

### 완료된

비동기 작업이 성공적으로 완료되면 future는 값을 가지고 완료됩니다. 그렇지 않으면 오류와 함께 완료됩니다.
#### Completing with a value

A future of type `Future<T>` completes with a value of type `T`. For example, a future with type `Future<String>` produces a string value. If a future doesn't produce a usable value, then the future's type is `Future<void>`.

### 값으로 완료

Future\<T> 타입의 future는 T 타입의 값을 가지고 완료됩니다. 예를 들어, Future\<String> 타입의 future는 문자열 값을 생성합니다. 값이 없는 경우에는 Future\<void> 타입의 future가 됩니다.

#### Completing with an error

If the asynchronous operation performed by the function fails for any reason, the future completes with an error.

### 오류로 완료

함수가 수행하는 비동기 작업이 어떤 이유로든 실패하면 future는 오류와 함께 완료됩니다.

### Example: Introducing futures

In the following example, `fetchUserOrder()` returns a future that completes after printing to the console. Because it doesn't return a usable value, `fetchUserOrder()` has the type `Future<void>`. Before you run the example, try to predict which will print first: "Large Latte" or "Fetching user order...".

### 예제: Future 소개

다음 예제에서 fetchUserOrder()는 콘솔에 출력을 마친 후 완료되는 future를 반환합니다. 사용 가능한 값을 직접 반환하지 않기 때문에 fetchUserOrder()는 Future\<void> 타입을 가집니다. 예제를 실행하기 전에 "Large Latte"와 "Fetching user order..." 중 어느 것이 먼저 출력될지 예상해 보세요.

```dart
Future<void> fetchUserOrder() {
  // Imagine that this function is fetching user info from another service or database.
  return Future.delayed(const Duration(seconds: 2), () => print('Large Latte'));
}

void main() {
  fetchUserOrder();
  print('Fetching user order...');
}
```

```
Fetching user order...
Large Latte
```

In the preceding example, even though `fetchUserOrder()` executes before the `print()` call on line 8, the console shows the output from line 8("Fetching user order...") before the output from `fetchUserOrder()` ("Large Latte"). This is because `fetchUserOrder()` delays before it prints "Large Latte".

이전 예제에서는 fetchUserOrder()가 print() 호출보다 먼저 실행되지만, 콘솔에서는 fetchUserOrder()의 출력("Large Latte")보다 먼저 line 8의 출력("Fetching user order...")이 나타납니다. 이는 fetchUserOrder()가 "Large Latte"를 출력하기 전에 지연되기 때문입니다.

### Example: Completing with an error

Run the following example to see how a future completes with an error. A bit later you'll learn how to handle the error.

### 예제: 오류로 완료

다음 예제를 실행하여 future가 오류와 함께 완료되는 방법을 살펴보세요. 곧이어 오류를 처리하는 방법에 대해 배우게 됩니다.

```dart
Future<void> fetchUserOrder() {
  // Imagine that this function is fetching user info but encounters a bug.
  return Future.delayed(
    const Duration(seconds: 2),
    () => throw Exception('Logout failed: user ID is invalid'),
  );
}

void main() {
  fetchUserOrder();
  print('Fetching user order...');
}
```

```
Fetching user order...
DartPad caught unhandled _Exception:
Exception: Logout failed: user ID is invalid
...
```

In this example, `fetchUserOrder()` completes with an error indicating that the user ID is invalid.

You've learned about futures and how they complete, but how do you use the results of asynchronous functions? In the next section you'll learn how to get results with the `async` and `await` keywords.

이 예제에서는, fetchUserOrder() 완료될 때 사용자 ID가 잘못되었음을 나타내는 오류가 발생합니다.

비동기 함수의 결과를 어떻게 사용하는지에 대해 배우셨지만, 다음 섹션에서는 async 및 await 키워드를 사용하여 결과를 어떻게 얻는지에 대해 배우게 될 것입니다.

**Quick review**

- A [Future\<T>](https://api.dart.dev/stable/dart-async/Future-class.html) instance produces a value of type `T`.
- If a future doesn't produce a usable value, then the future's type is `Future<void>`.
- A future can be in one of two states: uncompleted or completed.
- When you call a function that returns a future, the function queues up work to be done and returns an uncompleted future.
- When a future's operation finishes, the future completes with a value or with an error.

**Key terms:**

- **Future**: the Dart [Future](https://api.dart.dev/stable/dart-async/Future-class.html) class.
- **future**: an instance of the Dart `Future` class.

**Quick review**

- Future \<T> 인스턴스는 타입 T의 값을 생성합니다.
- 만약 future가 사용 가능한 값을 생성하지 않는다면, future의 타입은 Future\<void>입니다.
- future는 미완료 또는 완료 두 가지 상태 중 하나에 있을 수 있습니다.
- future를 반환하는 함수를 호출하면, 함수는 수행할 작업을 대기열에 추가하고 미완료된 future를 반환합니다.
- future의 작업이 완료되면, future는 값 또는 오류와 함께 완료됩니다.

**Key terms:**

- Future: Dart의 Future 클래스.
- future: Dart의 Future 클래스의 인스턴스.

## Working with futures: async and await

The `async` and `await` keywords provide a declarative way to define asynchronous functions and use their results. Remember these two basic guidelines when using `async` and `await`:

- **To define an async function, add `async` before the function body:**
- **The `await` keyword works only in `async` functions.**

Here's an example that converts `main()` from a synchronous to asynchronous function.

First, add the `async` keyword before the function body:

## "Futures와 함께 작업하기: async와 await

async와 await 키워드는 비동기 함수를 정의하고 그 결과를 사용하는 선언적인 방법을 제공합니다. async와 await를 사용할 때 기본적으로 알아야 할 두 가지 지침이 있습니다:

- 비동기 함수를 정의하려면 함수 본문 앞에 async를 추가합니다.
- await 키워드는 오직 async 함수 내에서만 작동합니다.

다음은 main() 함수를 동기적인 함수에서 비동기적인 함수로 변환하는 예제입니다.

먼저 함수 본문 앞에 async 키워드를 추가하세요."

```dart
void main() async { ··· }
```

If the function has a declared return type, then update the type to be `Future<T>`, where `T` is the type of the value that the function returns. If the function doesn't explicitly return a value, then the return type is `Future<void>`:

만약 함수가 명시적으로 반환 타입을 가진 경우, 해당 타입을 함수가 반환하는 값의 타입 T로 업데이트합니다. 함수가 명시적으로 값을 반환하지 않는 경우, 반환 타입은 Future\<void>가 됩니다.

```dart
Future<void> main() async { ··· }
```

Now that you have an `async` function, you can use the `await` keyword to wait for a future to complete:

이제 async 함수를 사용하여 await 키워드를 사용하여 future가 완료될 때까지 기다릴 수 있습니다.

```dart
print(await createOrderMessage());
```

As the following two examples show, the `async` and `await` keywords result in asynchronous code that looks a lot like synchronous code. The only differences are highlighted in the asynchronous example, which—if your window is wide enough—is to the right of the synchronous example.

다음 두 예제에서 볼 수 있듯이, async와 await 키워드는 동기 코드와 매우 비슷한 비동기 코드를 만듭니다. 윈도우가 충분히 넓다면 동기 예제의 오른쪽에 비동기 예제가 표시됩니다.

#### Example: synchronous functions

```dart
String createOrderMessage() {
  var order = fetchUserOrder();
  return 'Your order is: $order';
}

Future<String> fetchUserOrder() =>
    // Imagine that this function is
    // more complex and slow.
    Future.delayed(
      const Duration(seconds: 2),
      () => 'Large Latte',
    );

void main() {
  print('Fetching user order...');
  print(createOrderMessage());
}
```

```
Fetching user order...
Your order is: Instance of '_Future<String>'
```

#### Example: asynchronous functions

```dart
Future<String> createOrderMessage() async {
  var order = await fetchUserOrder();
  return 'Your order is: $order';
}

Future<String> fetchUserOrder() =>
    // Imagine that this function is
    // more complex and slow.
    Future.delayed(
      const Duration(seconds: 2),
      () => 'Large Latte',
    );

Future<void> main() async {
  print('Fetching user order...');
  print(await createOrderMessage());
}
```

```
Fetching user order...
Your order is: Large Latte
```

The asynchronous example is different in three ways:

- The return type for `createOrderMessage()` changes from `String` to `Future<String>`.
- The **`async`** keyword appears before the function bodies for `createOrderMessage()` and `main()`.
- The **`await`** keyword appears before calling the asynchronous functions `fetchUserOrder()` and `createOrderMessage()`.

비동기 예제는 세 가지 점에서 다릅니다:

- createOrderMessage()의 반환 타입이 String에서 Future\<String>으로 바뀝니다.
- createOrderMessage()와 main() 함수의 본문 앞에 async 키워드가 추가됩니다.
- fetchUserOrder()와 createOrderMessage()를 호출할 때 async 함수 앞에 await 키워드가 사용됩니다.

Key terms

- **async**: You can use the `async` keyword before a function's body to mark it as asynchronous.
- **async function**: An `async` function is a function labeled with the `async` keyword.
- **await**: You can use the `await` keyword to get the completed result of an asynchronous expression. The `await` keyword only works within an `async` function.

Key terms

- async: 함수 본문 앞에 async 키워드를 사용하여 해당 함수를 비동기 함수로 표시할 수 있습니다.
- async function: async 키워드가 표시된 함수를 async 함수라고 합니다.
- await: await 키워드를 사용하여 비동기 표현식의 완료된 결과를 얻을 수 있습니다. await 키워드는 async 함수 내에서만 작동합니다.

### Execution flow with async and await

An `async` function runs synchronously until the first `await` keyword. This means that within an `async` function body, all synchronous code before the first `await` keyword executes immediately.

### async와 await를 사용한 실행 흐름

`async` 함수는 첫 번째 `await` 키워드를 만날 때까지 동기적으로 실행됩니다. 이는 `async` 함수 본문 내에서 첫 번째 `await` 키워드 이전의 모든 동기 코드가 즉시 실행된다는 것을 의미합니다.

### Example: Execution within async functions

Run the following example to see how execution proceeds within an `async` function body. What do you think the output will be?

### 예제: async 함수 내의 실행 흐름

다음 예제를 실행하여 `async` 함수 본문 내에서 실행이 어떻게 진행되는지 확인하세요. 출력 결과는 어떻게 될지 예상해 보세요.

```dart
Future<void> printOrderMessage() async {
  print('Awaiting user order...');
  var order = await fetchUserOrder();
  print('Your order is: $order');
}

Future<String> fetchUserOrder() {
  // Imagine that this function is more complex and slow.
  return Future.delayed(const Duration(seconds: 4), () => 'Large Latte');
}

void main() async {
  countSeconds(4);
  await printOrderMessage();
}

// You can ignore this function - it's here to visualize delay time in this example.
void countSeconds(int s) {
  for (var i = 1; i <= s; i++) {
    Future.delayed(Duration(seconds: i), () => print(i));
  }
}
```

```
Awaiting user order...
1
2
3
4
Your order is: Large Latte

```

After running the code in the preceding example, try reversing lines 2 and 3:

이전 예제의 코드를 실행한 후에는, 2번째와 3번째 줄을 서로 바꿔보세요.

```dart
var order = await fetchUserOrder();
print('Awaiting user order...');
```

Notice that timing of the output shifts, now that `print('Awaiting user order')` appears after the first `await` keyword in `printOrderMessage()`.

알림: 출력의 타이밍이 변경된 것을 주목하세요. 이제 `print('Awaiting user order')`가 `printOrderMessage()`의 첫 번째 `await` 키워드 이후에 나타나기 때문입니다.

### Exercise: Practice using async and await

The following exercise is a failing unit test that contains partially completed code snippets. Your task is to complete the exercise by writing code to make the tests pass. You don't need to implement `main()`.

To simulate asynchronous operations, call the following functions, which are provided for you:

| Function           | Type signature                   | Description                                    |
| ------------------ | -------------------------------- | ---------------------------------------------- |
| fetchRole()        | `Future<String> fetchRole()`     | Gets a short description of the user's role.   |
| fetchLoginAmount() | `Future<int> fetchLoginAmount()` | Gets the number of times a user has logged in. |
### 연습 문제: async와 await 사용 연습

다음 연습 문제는 실패하는 유닛 테스트이며, 부분적으로 완성된 코드 스니펫이 포함되어 있습니다. 여러분의 작업은 이 연습 문제를 완성하여 테스트가 통과하도록 코드를 작성하는 것입니다. `main()` 함수를 구현할 필요는 없습니다.

비동기 작업을 시뮬레이션하기 위해 다음 함수들을 호출하세요.

| Function           | Type signature                   | Description               |
| ------------------ | -------------------------------- | ------------------------- |
| fetchRole()        | `Future<String> fetchRole()`     | 사용자 역할에 대한 간단한 설명을 가져옵니다. |
| fetchLoginAmount() | `Future<int> fetchLoginAmount()` | 사용자가 로그인한 횟수를 가져옵니다.      |
#### Part 1: `reportUserRole()`

Add code to the `reportUserRole()` function so that it does the following:

- Returns a future that completes with the following string: `"User role: <user role>"`
    - Note: You must use the actual value returned by `fetchRole()`; copying and pasting the example return value won't make the test pass.
    - Example return value: `"User role: tester"`
- Gets the user role by calling the provided function `fetchRole()`.
- 
#### Part 1: `reportUserRole()`

`reportUserRole()` 함수에 다음 코드를 추가하여 다음 작업을 수행하도록 하세요:

- 다음 문자열로 완료되는 Future를 반환합니다: `"User role: <user role>"`.
    - 참고: `fetchRole()`에서 반환된 실제 값을 사용해야 합니다. 예제 반환 값을 복사하여 붙여넣어서는 테스트를 통과할 수 없습니다.
    - 예제 반환 값: `"User role: tester"`
- 제공된 함수 `fetchRole()`를 호출하여 사용자 역할을 가져옵니다.
#### Part 2: `reportLogins()`

Implement an `async` function `reportLogins()` so that it does the following:

- Returns the string `"Total number of logins: <# of logins>"`.
    - Note: You must use the actual value returned by `fetchLoginAmount()`; copying and pasting the example return value won't make the test pass.
    - Example return value from `reportLogins()`: `"Total number of logins: 57"`
- Gets the number of logins by calling the provided function `fetchLoginAmount()`.

#### Part 2: `reportLogins()`

`async` 함수 `reportLogins()`를 구현하여 다음 작업을 수행하도록 하세요:

- 문자열 `"Total number of logins: <# of logins>"`을 반환합니다.
    - 참고: `fetchLoginAmount()`에서 반환된 실제 값을 사용해야 합니다. 예제 반환 값을 복사하여 붙여넣어서는 테스트를 통과할 수 없습니다.
    - `reportLogins()`의 예제 반환 값: `"Total number of logins: 57"`
- 제공된 함수 `fetchLoginAmount()`를 호출하여 로그인 횟수를 가져옵니다.

```dart
// Part 1
// Call the provided async function fetchRole()
// to return the user role.
Future<String> reportUserRole() async {
  // TODO: Implement the reportUserRole function here.
}

// Part 2
// TODO: Implement the reportLogins function here.
// Call the provided async function fetchLoginAmount()
// to return the number of times that the user has logged in.
reportLogins() {}

// The following functions those provided to you to simulate
// asynchronous operations that could take a while.

Future<String> fetchRole() => Future.delayed(_halfSecond, () => _role);
Future<int> fetchLoginAmount() => Future.delayed(_halfSecond, () => _logins);

// The following code is used to test and provide feedback on your solution.
// There is no need to read or modify it.

void main() async {
  print('Testing...');
  List<String> messages = [];
  const passed = 'PASSED';
  const testFailedMessage = 'Test failed for the function:';
  const typoMessage = 'Test failed! Check for typos in your return value';
  try {
    messages
      ..add(_makeReadable(
          testLabel: 'Part 1',
          testResult: await _asyncEquals(
            expected: 'User role: administrator',
            actual: await reportUserRole(),
            typoKeyword: _role,
          ),
          readableErrors: {
            typoMessage: typoMessage,
            'null':
                'Test failed! Did you forget to implement or return from reportUserRole?',
            'User role: Instance of \'Future<String>\'':
                '$testFailedMessage reportUserRole. Did you use the await keyword?',
            'User role: Instance of \'_Future<String>\'':
                '$testFailedMessage reportUserRole. Did you use the await keyword?',
            'User role:':
                '$testFailedMessage reportUserRole. Did you return a user role?',
            'User role: ':
                '$testFailedMessage reportUserRole. Did you return a user role?',
            'User role: tester':
                '$testFailedMessage reportUserRole. Did you invoke fetchRole to fetch the user\'s role?',
          }))
      ..add(_makeReadable(
          testLabel: 'Part 2',
          testResult: await _asyncEquals(
            expected: 'Total number of logins: 42',
            actual: await reportLogins(),
            typoKeyword: _logins.toString(),
          ),
          readableErrors: {
            typoMessage: typoMessage,
            'null':
                'Test failed! Did you forget to implement or return from reportLogins?',
            'Total number of logins: Instance of \'Future<int>\'':
                '$testFailedMessage reportLogins. Did you use the await keyword?',
            'Total number of logins: Instance of \'_Future<int>\'':
                '$testFailedMessage reportLogins. Did you use the await keyword?',
            'Total number of logins: ':
                '$testFailedMessage reportLogins. Did you return the number of logins?',
            'Total number of logins:':
                '$testFailedMessage reportLogins. Did you return the number of logins?',
            'Total number of logins: 57':
                '$testFailedMessage reportLogins. Did you invoke fetchLoginAmount to fetch the number of user logins?',
          }))
      ..removeWhere((m) => m.contains(passed))
      ..toList();

    if (messages.isEmpty) {
      print('Success. All tests passed!');
    } else {
      messages.forEach(print);
    }
  } on UnimplementedError {
    print(
        'Test failed! Did you forget to implement or return from reportUserRole?');
  } catch (e) {
    print('Tried to run solution, but received an exception: $e');
  }
}

const _role = 'administrator';
const _logins = 42;
const _halfSecond = Duration(milliseconds: 500);

// Test helpers.
String _makeReadable({
  required String testResult,
  required Map<String, String> readableErrors,
  required String testLabel,
}) {
  if (readableErrors.containsKey(testResult)) {
    var readable = readableErrors[testResult];
    return '$testLabel $readable';
  } else {
    return '$testLabel $testResult';
  }
}

// Assertions used in tests.
Future<String> _asyncEquals({
  required String expected,
  required dynamic actual,
  required String typoKeyword,
}) async {
  var strActual = actual is String ? actual : actual.toString();
  try {
    if (expected == actual) {
      return 'PASSED';
    } else if (strActual.contains(typoKeyword)) {
      return 'Test failed! Check for typos in your return value';
    } else {
      return strActual;
    }
  } catch (e) {
    return e.toString();
  }
}
```


Hint

Did you remember to add the `async` keyword to the `reportUserRole` function?

Did you remember to use the `await` keyword before invoking `fetchRole()`?

Remember: `reportUserRole` needs to return a `Future`.

`reportUserRole` 함수에 `async` 키워드를 추가했는지 확인하세요.

`fetchRole()`를 호출하기 전에 `await` 키워드를 사용했는지 확인하세요.

`reportUserRole`이 Future를 반환해야 한다는 것을 기억하세요.



Solution

```dart
Future<String> reportUserRole() async {
  final username = await fetchRole();
  return 'User role: $username';
}

Future<String> reportLogins() async {
  final logins = await fetchLoginAmount();
  return 'Total number of logins: $logins';
}
```

## Handling errors

To handle errors in an `async` function, use try-catch:

## 에러 핸들링

비동기 함수에서 오류를 처리하려면, try-catch를 사용하세요:

```dart
try {
  print('Awaiting user order...');
  var order = await fetchUserOrder();
} catch (err) {
  print('Caught error: $err');
}
```

Within an `async` function, you can write [try-catch clauses](https://dart.dev/language/error-handling#catch) the same way you would in synchronous code.

비동기 함수 내에서, 동기 코드에서와 동일한 방식으로 try-catch 절을 작성할 수 있습니다.
### Example: async and await with try-catch

Run the following example to see how to handle an error from an asynchronous function. What do you think the output will be?

### 예제: try-catch를 사용한 async 및 await

비동기 함수에서 오류를 처리하는 방법을 보기 위해 다음 예제를 실행하세요. 출력이 어떻게 될 것 같나요?

```dart
Future<void> printOrderMessage() async {
  try {
    print('Awaiting user order...');
    var order = await fetchUserOrder();
    print(order);
  } catch (err) {
    print('Caught error: $err');
  }
}

Future<String> fetchUserOrder() {
  // Imagine that this function is more complex.
  var str = Future.delayed(
      const Duration(seconds: 4),
      () => throw 'Cannot locate user order');
  return str;
}

void main() async {
  await printOrderMessage();
```

```
Awaiting user order...
Caught error: Cannot locate user order
```

### Exercise: Practice handling errors

The following exercise provides practice handling errors with asynchronous code, using the approach described in the previous section. To simulate asynchronous operations, your code will call the following function, which is provided for you:

|Function|Type signature|Description|
|---|---|---|
|fetchNewUsername()|`Future<String> fetchNewUsername()`|Returns the new username that you can use to replace an old one.|

Use `async` and `await` to implement an asynchronous `changeUsername()` function that does the following:

- Calls the provided asynchronous function `fetchNewUsername()` and returns its result.
    - Example return value from `changeUsername()`: `"jane_smith_92"`
- Catches any error that occurs and returns the string value of the error.
    - You can use the [toString()](https://api.dart.dev/stable/dart-core/ArgumentError/toString.html) method to stringify both [Exceptions](https://api.dart.dev/stable/dart-core/Exception-class.html) and [Errors.](https://api.dart.dev/stable/dart-core/Error-class.html)

### 연습: 오류 처리 연습

다음 연습에서는 이전 섹션에서 설명한 접근 방식을 사용하여 비동기 코드로 오류를 처리하는 연습을 제공합니다. 비동기 작업을 시뮬레이션하기 위해, 제공된 다음 함수를 호출하는 코드를 작성할 것입니다:

|함수|타입 서명|설명|
|---|---|---|
|fetchNewUsername()|`Future<String> fetchNewUsername()`|이전 사용자 이름을 대체할 수 있는 새 사용자 이름을 반환합니다.|

`async`와 `await`를 사용하여 다음 작업을 수행하는 비동기 `changeUsername()` 함수를 구현하세요:

- 제공된 비동기 함수 `fetchNewUsername()`을 호출하고 그 결과를 반환합니다. 
	- `changeUsername()` 함수의 예제 반환 값은 `"jane_smith_92"`입니다. 
- 발생하는 모든 오류를 처리하고 오류의 문자열 값을 반환합니다. 
	- 오류를 문자열로 변환하기 위해 `toString()` 메서드를 사용할 수 있습니다.

```dart
// TODO: Implement changeUsername here.
changeUsername() {}

// The following function is provided to you to simulate
// an asynchronous operation that could take a while and
// potentially throw an exception.

Future<String> fetchNewUsername() =>
    Future.delayed(const Duration(milliseconds: 500), () => throw UserError());

class UserError implements Exception {
  @override
  String toString() => 'New username is invalid';
}

// The following code is used to test and provide feedback on your solution.
// There is no need to read or modify it.

void main() async {
  final List<String> messages = [];
  const typoMessage = 'Test failed! Check for typos in your return value';

  print('Testing...');
  try {
    messages
      ..add(_makeReadable(
          testLabel: '',
          testResult: await _asyncDidCatchException(changeUsername),
          readableErrors: {
            typoMessage: typoMessage,
            _noCatch:
                'Did you remember to call fetchNewUsername within a try/catch block?',
          }))
      ..add(_makeReadable(
          testLabel: '',
          testResult: await _asyncErrorEquals(changeUsername),
          readableErrors: {
            typoMessage: typoMessage,
            _noCatch:
                'Did you remember to call fetchNewUsername within a try/catch block?',
          }))
      ..removeWhere((m) => m.contains(_passed))
      ..toList();

    if (messages.isEmpty) {
      print('Success. All tests passed!');
    } else {
      messages.forEach(print);
    }
  } catch (e) {
    print('Tried to run solution, but received an exception: $e');
  }
}

// Test helpers.
String _makeReadable({
  required String testResult,
  required Map<String, String> readableErrors,
  required String testLabel,
}) {
  if (readableErrors.containsKey(testResult)) {
    final readable = readableErrors[testResult];
    return '$testLabel $readable';
  } else {
    return '$testLabel $testResult';
  }
}

Future<String> _asyncErrorEquals(Function fn) async {
  final result = await fn();
  if (result == UserError().toString()) {
    return _passed;
  } else {
    return 'Test failed! Did you stringify and return the caught error?';
  }
}

Future<String> _asyncDidCatchException(Function fn) async {
  var caught = true;
  try {
    await fn();
  } on UserError catch (_) {
    caught = false;
  }

  if (caught == false) {
    return _noCatch;
  } else {
    return _passed;
  }
}

const _passed = 'PASSED';
const _noCatch = 'NO_CATCH';
```

Hint

Implement `changeUsername` to return the string from `fetchNewUsername` or, if that fails, the string value of any error that occurs.

Remember: You can use a [try-catch statement](https://dart.dev/language/error-handling#catch) to catch and handle errors.

changeUsername 함수를 구현하여 fetchNewUsername에서 반환된 문자열을 반환하거나, 그것이 실패할 경우 발생한 어떤 오류의 문자열 값을 반환합니다.

참고: try-catch 문을 사용하여 오류를 잡고 처리할 수 있습니다.

```dart
Future<String> changeUsername() async {
  try {
    return await fetchNewUsername();
  } catch (err) {
    return err.toString();
  }
}
```
## Exercise: Putting it all together

It's time to practice what you've learned in one final exercise. To simulate asynchronous operations, this exercise provides the asynchronous functions `fetchUsername()` and `logoutUser()`:

|Function|Type signature|Description|
|---|---|---|
|fetchUsername()|`Future<String> fetchUsername()`|Returns the name associated with the current user.|
|logoutUser()|`Future<String> logoutUser()`|Performs logout of current user and returns the username that was logged out.|
## 연습: 모두 함께 적용해보기

이제 여태까지 배운 것들을 실전에서 연습해보는 시간입니다. 비동기 작업을 시뮬레이션하기 위해 사용할 함수들은 `fetchUsername()`과 `logoutUser()`입니다:

|함수|타입 시그니처|설명|
|---|---|---|
|fetchUsername()|`Future<String> fetchUsername()`|현재 사용자와 관련된 이름을 반환합니다.|
|logoutUser()|`Future<String> logoutUser()`|현재 사용자를 로그아웃하고 로그아웃된 사용자의 이름을 반환합니다.|

Write the following:

#### Part 1: `addHello()`

[#](https://dart.dev/libraries/async/async-await#part-1-addhello)

- Write a function `addHello()` that takes a single `String` argument.
- `addHello()` returns its `String` argument preceded by `'Hello '`.  
    Example: `addHello('Jon')` returns `'Hello Jon'`.

### Part 1: addHello()

- 하나의 문자열 인자를 받는 함수 addHello()를 작성합니다. 
- addHello()는 주어진 문자열 인자 앞에 'Hello '를 붙여서 반환합니다. 
	예시: addHello('Jon')은 'Hello Jon'을 반환합니다.

#### Part 2: `greetUser()`

- Write a function `greetUser()` that takes no arguments.
- To get the username, `greetUser()` calls the provided asynchronous function `fetchUsername()`.
- `greetUser()` creates a greeting for the user by calling `addHello()`, passing it the username, and returning the result.  
    Example: If `fetchUsername()` returns `'Jenny'`, then `greetUser()` returns `'Hello Jenny'`.

### Part 2: greetUser()

- 인자를 받지 않는 함수 greetUser()를 작성합니다. 
- 사용자 이름을 가져오기 위해 greetUser()는 제공된 비동기 함수 fetchUsername()을 호출합니다. 
- greetUser()는 사용자 이름을 addHello()를 호출하여 인사말을 생성하고 그 결과를 반환합니다. 
	예시: fetchUsername()이 'Jenny'를 반환하면 greetUser()는 'Hello Jenny'를 반환합니다.

#### Part 3: `sayGoodbye()`

- Write a function `sayGoodbye()` that does the following:
    - Takes no arguments.
    - Catches any errors.
    - Calls the provided asynchronous function `logoutUser()`.
- If `logoutUser()` fails, `sayGoodbye()` returns any string you like.
- If `logoutUser()` succeeds, `sayGoodbye()` returns the string `'<result> Thanks, see you next time'`, where `<result>` is the string value returned by calling `logoutUser()`.

### Part 3: sayGoodbye()

- 다음과 같이 동작하는 함수 sayGoodbye()를 작성합니다: 
	- 인자를 받지 않습니다. 
	- 모든 오류를 잡습니다. 
	- 제공된 비동기 함수 logoutUser()를 호출합니다. 
- 만약 logoutUser() 호출이 실패하면, sayGoodbye()는 임의의 문자열을 반환합니다. 
- 만약 logoutUser() 호출이 성공하면, sayGoodbye()는 '\<result> Thanks, see you next time' 형식의 문자열을 반환합니다. 여기서 \<result>는 logoutUser() 호출의 반환 값입니다.



Hint

The greetUser와 sayGoodbye 함수는 비동기여야 하며, addHello는 일반 동기 함수여야 합니다.

The `greetUser` and `sayGoodbye` functions should be asynchronous, while `addHello` should be a normal, synchronous function.

Remember: You can use a [try-catch statement](https://dart.dev/language/error-handling#catch) to catch and handle errors.

참고: 오류를 잡고 처리하기 위해 try-catch 문을 사용할 수 있습니다.

Solution

```dart
String addHello(String user) => 'Hello $user';

Future<String> greetUser() async {
  final username = await fetchUsername();
  return addHello(username);
}

Future<String> sayGoodbye() async {
  try {
    final result = await logoutUser();
    return '$result Thanks, see you next time';
  } catch (e) {
    return 'Failed to logout user: $e';
  }
}
```
